### PR TITLE
Support eclipse; targetCompatibility=1.6 explicit; corrected codenarc co...

### PR DESCRIPTION
**Pull request by kktec**
I do not have Java6 installed so targetCompatibility stops java.lang.VerifyError

### CODE REVIEW

**Comment by craigburke** [comment]
Beautiful! Thanks, man!

**Comment by craigburke** [comment]
The first of many contributions to this project I'm hoping :wink:

**Comment by kktec** [comment]
Hopefully, but I at least hope to be able to steal some of your good ideas for my own gsheets project, https://github.com/kktec/gsheets

**Comment by craigburke** [comment]
@kktec yeah I saw that project, that's very cool! I've been meaning to dig into it to see if I could steal any ideas as well :)

**Pull request merged**
